// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7LCagz6bUI1oznv7zqt1fOwQaQ067qyE',
    appId: '1:738411522801:web:f76ca96bd849d8b1af9750',
    messagingSenderId: '738411522801',
    projectId: 'kedelai-hub',
    authDomain: 'kedelai-hub.firebaseapp.com',
    storageBucket: 'kedelai-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIFE3UCt0ouHnMpHg5NxCRDNK05G1b2VU',
    appId: '1:738411522801:android:1243f0924afbe89baf9750',
    messagingSenderId: '738411522801',
    projectId: 'kedelai-hub',
    storageBucket: 'kedelai-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM8y3cD1cj9AJ8PZ5hdTtDHwYxWWW_jYs',
    appId: '1:738411522801:ios:7f95803c8ed50bb8af9750',
    messagingSenderId: '738411522801',
    projectId: 'kedelai-hub',
    storageBucket: 'kedelai-hub.appspot.com',
    iosBundleId: 'umm.kedelaiHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM8y3cD1cj9AJ8PZ5hdTtDHwYxWWW_jYs',
    appId: '1:738411522801:ios:7f95803c8ed50bb8af9750',
    messagingSenderId: '738411522801',
    projectId: 'kedelai-hub',
    storageBucket: 'kedelai-hub.appspot.com',
    iosBundleId: 'umm.kedelaiHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7LCagz6bUI1oznv7zqt1fOwQaQ067qyE',
    appId: '1:738411522801:web:15e0370efca0b1afaf9750',
    messagingSenderId: '738411522801',
    projectId: 'kedelai-hub',
    authDomain: 'kedelai-hub.firebaseapp.com',
    storageBucket: 'kedelai-hub.appspot.com',
  );
}
